# Generated by Django 3.0 on 2020-02-26 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200226_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='product_name',
            field=models.CharField(choices=[('uav_30cm', 'UAV 30')], max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('832c7395-de3f-4653-bcf3-86b81dac2560'), unique=True),
        ),
    ]
