# Generated by Django 3.0.3 on 2020-02-26 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200226_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a3269cb3-fbe4-4357-b006-bb84fdfbf69b'), unique=True),
        ),
    ]
