# Generated by Django 3.0.3 on 2020-02-26 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20200226_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('72a1dbdb-69b4-4e0b-800f-c1ae85b721e0'), unique=True),
        ),
    ]
