# Generated by Django 3.0.3 on 2020-02-26 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='name',
            field=models.CharField(default=uuid.UUID('fdec1365-6103-4e0a-ac0a-0c4188850d4c'), help_text='Short Description For This Task', max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
