# Generated by Django 3.0.3 on 2020-02-26 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20200226_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='name',
            field=models.CharField(default=uuid.UUID('0b96c8b0-4745-4413-92fe-7d8853472077'), help_text='Short Description For This Task', max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
