# Generated by Django 3.0.3 on 2020-02-26 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20200226_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='name',
            field=models.CharField(default=uuid.UUID('5f2667b6-3921-4592-b3bb-1952e9a61b19'), help_text='Short Description For This Task', max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
