# Generated by Django 2.2 on 2020-02-24 16:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoi', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
