# Generated by Django 3.0 on 2020-02-20 06:07

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (' Image id', models.UUIDField(unique=True)),
                ('title', models.CharField(default='', max_length=80)),
                ('creation_date', models.DateField(verbose_name='Creation Date')),
                ('ingestion_date', models.DateField(verbose_name='Ingestion Date')),
                ('footprint', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('link', models.CharField(default='', max_length=200)),
                ('size', models.CharField(default='0 GB', max_length=30)),
                ('original_image_src', models.CharField(default='', max_length=200)),
                ('processed_image_src', models.CharField(default='', max_length=200)),
                ('end_execution_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='end_execution_time')),
            ],
        ),
    ]
