# Generated by Django 3.0 on 2020-02-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadmodel',
            old_name=' Image id',
            new_name='uuid',
        ),
    ]
